### ISSUE TITLE
[Forwarder]: Implement Interface for remote terminal/device forwarder feature

### ISSUE THREAD

**Issue by harlem88** [edgehog-device-manager/edgehog-device-runtime#274]
Some information such as the ip/port/secrect etc for connecting to the websocket will be received through an Astarte interface.

**Comment by rgallor** [comment]
What do you think of `io.edgehog.devicemanager.RemoteShell` as the name for the interface?

**Comment by rgallor** [comment]
I've made a PR in [edgehog-astarte-interfaces](https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/pull/63)
