### ISSUE TITLE
[Hardware-id]: Update Cargo lock dependencies

### ISSUE THREAD

**Issue by harlem88** [edgehog-device-manager/edgehog-device-runtime#379]
the last update of [Cargo.lock](https://github.com/edgehog-device-manager/edgehog-device-runtime/blob/main/hardware-id-service/Cargo.lock) goes back two years ago.

**Comment by joshuachp** [comment]
I believe the `Cargo.lock` is no longer used, since the package is part of the workspace, and can be safely deleted.
